services:
    coop_tilleuls_forgot_password.controller.forgot_password:
        class:     'CoopTilleuls\ForgotPasswordBundle\Controller\ForgotPasswordController'
        arguments: ['@coop_tilleuls_forgot_password.manager.forgot_password', '@coop_tilleuls_forgot_password.manager.password_token', '%coop_tilleuls_forgot_password.user_field%']

    coop_tilleuls_forgot_password.manager.forgot_password:
        class:     'CoopTilleuls\ForgotPasswordBundle\Manager\ForgotPasswordManager'
        arguments: ['@security.token_storage', '@request_stack', '@coop_tilleuls_forgot_password.manager.password_token', '@event_dispatcher', '@doctrine', '%coop_tilleuls_forgot_password.user_class%', '%coop_tilleuls_forgot_password.user_field%']

    coop_tilleuls_forgot_password.manager.password_token:
        class:     'CoopTilleuls\ForgotPasswordBundle\Manager\PasswordTokenManager'
        arguments: ['@doctrine', '%coop_tilleuls_forgot_password.password_token_class%']
